### ISSUE TITLE
Message is not unmarshalled into response struct correctly

### ISSUE THREAD

**Issue by scottjbarr** [fiorix/wsdl2go#10]
I have created a working version (using a specific struct, rather than the Message interface used by the generated Client)...

https://play.golang.org/p/9S0Jzk9_C-

and a version that uses the Message interface. Again, this is isolated code from a generated Client.

https://play.golang.org/p/czWZqKEUgG

Has anyone seen the structs being populated correctly when using the `Message` interface in `Body`?

Using a []byte instead of a Message interface seems to work.

https://play.golang.org/p/qFY2hj5Lnv

If you are happy with this option I would supply a fix. Thoughts?

**Comment by fiorix** [comment]
Maybe we should try again after the recent fixes.
