### ISSUE TITLE
Client decoder

### ISSUE THREAD

**Issue by AlexDias79** [fiorix/wsdl2go#103]
Hello, 

First of all congrats for this nice tool, you did a great job with it.

So, I came across some error and I'm not sure why but it seems to be related with the client doRoundTrip()

Unmarshling the byte array from resp.body (using ioutil.ReadAll(resp.Body) I can see the whole correct xml response
`<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soap:Body>
      <HelloWorldResponse xmlns="http://localhost:8282/">
         <HelloWorldResult>Yey, it works</HelloWorldResult>
      </HelloWorldResponse>
   </soap:Body>
</soap:Envelope`

The marshalStructure.XMLName is just fine, so it did unmarshal correct. Thing is, the body didn't and i can't figure out why and how to correct that.
`
	marshalStructure := struct {
		XMLName xml.Name `xml:"Envelope"`
		Body    Message  `xml:"Body"`
	}{Body: out}

	err = xml.NewDecoder(resp.Body).Decode(&marshalStructure)
	fmt.Println(marshalStructure.XMLName) //<-- correct | {http://schemas.xmlsoap.org/soap/envelope/ Envelope}
	fmt.Println(marshalStructure.Body) // <-- nil pointer | &{{<nil>}}
	return err`

Any idea?

**Comment by fiorix** [comment]
Hmmmm I'm not sure what's going on here and this will need some manual investigation that unfortunately I don't have the time to do right now.

**Comment by fiorix** [comment]
Looks like dup of #90
