### ISSUE TITLE
Character encoding issues

### ISSUE THREAD

**Issue by digitalsparky** [fiorix/wsdl2go#109]
Hi, just letting you know there are character encoding issues with your current codebase.
I forked and fixed it, however, to do so requires an external package and I didn't want to break compatibility with a merge request.

For specific changes, look at:

https://github.com/fiorix/wsdl2go/compare/master...digitalsparky:master#diff-3bb06cfa05708bb86d2eec5ee5ce82b0

https://github.com/fiorix/wsdl2go/compare/master...digitalsparky:master#diff-3bf100299441d266b94b68671019fea5

https://github.com/fiorix/wsdl2go/compare/master...digitalsparky:master#diff-2131c557643029ee9e54fdf88e7388b0

Special note: I changed the namespace so I could continue to use it without breaking.

Also the full changes include the required vendor package via dep, which breaks < 1.9 golang compatibility, hence not wanting to merge.

Feel free to cherry pick those changes as needed.

Matt

**Comment by fiorix** [comment]
Thanks for sharing here. I'd be fine breaking compatibility with Go 1.9 and forcing it 1.10 onwards. I haven't been very active in this codebase and lately only reviewing code from contributors. I'd appreciate if you could cut a PR for this.

**Comment by digitalsparky** [comment]
fair enough, PR re-opened.

**Comment by digitalsparky** [comment]
This change was merged on #108, closing.
