### ISSUE TITLE
auth header problem

### ISSUE THREAD

**Issue by ferenc0521** [fiorix/wsdl2go#120]

**Comment by ferenc0521** [comment]
clic := soap.Client{
		URL: "http://triage:8080/ws/v9/configurationservice",
		Namespace: configurationserviceportbinding.Namespace,
		Header: soap.AuthHeader{Namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd",Username: "admin", Password: "coverity"},
	}

results in:
$ go run apiv9
2019/04/11 18:06:59 "401 Unauthorized": "<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S=\"http://schemas.xmlsoap.org/soap/envelope/\"><S:Body><S:Fault xmlns:ns4=\"http://www.w3.org/2003/05/soap-envelope\"><faultcode>S:Server</faultcode><faultstring>User authentication failed.</faultstring></S:Fault></S:Body></S:Envelope>"
exit status 1

the soap header from soapUI which works is:
<soapenv:Header>
<wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" soapenv:mustUnderstand="1">
<wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="XWSSGID-1349973313023-787497544">
<wsse:Username>admin</wsse:Username>
<wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">coverity</wsse:Password>
</wsse:UsernameToken>
</wsse:Security>
</soapenv:Header>   
which looks like Ineed a different namespace for the username and password too

**Comment by fiorix** [comment]
Timeout
