### ISSUE TITLE
Crash if operations in wsdl don't have an output policy

### ISSUE THREAD

**Issue by LostAstr0naut** [fiorix/wsdl2go#129]
I was playing around with Microsoft's WCF service and tried to generate go code from wsdl with this tool. I found out that if an operation only has an input policy but no output policy, it will crash.

 I'm referring to a piece of wsdl writing in similar fashion:
`<wsp:Policy wsu:Id="WSHttpBinding_IService_GetState_output_policy">
**...**
</wsp:Policy>`

My current workaround was to fix **encoder.go** in **wsdlgo** folder near line **1364**. I had to wrap that line with an if statement to make it work:
`if ge.funcs[bo.Name].Output != nil {
		ge.genOpStructMessage(w, d, name, ge.messages[trimns(ge.funcs[bo.Name].Output.Message)])
	})`

This issue should get looked at, as it actually makes the tool crash with an **invalid memory address or nil pointer dereference** error.

**Comment by denysvitali** [comment]
Uh, this might be related to my PR (#131), but I'm handling the case where only the Input is not defined

**Comment by denysvitali** [comment]
Fixed also the problem w/ the output. Can you please check and report back if it works? The PR is already merged

**Comment by tomzazo** [comment]
Unfortunately I don't have the setup anymore to be able to test this. Will test in the future.
