### ISSUE TITLE
Should not depend on $GOROOT to be defined

### ISSUE THREAD

**Issue by adriantam** [fiorix/wsdl2go#13]
According to https://golang.org/doc/install, GOROOT should be set only in the case where go binary distribution is installed to a custom location.  Otherwise, "The Go binary distributions assume they will be installed in /usr/local/go (or c:\Go under Windows)"

However, in wsdlgo/encoder.go, it requires GOROOT to be set.  A better solution is to assume /usr/local/go (or C:\Go in the case of windows) if GOROOT is not set.

**Comment by fiorix** [comment]
Alright, let's forget about env vars and blindly exec gofmt assuming it's on PATH then. I don't like the idea of hard coding paths in the binary.

**Comment by adriantam** [comment]
Changed to use path variable
