### ISSUE TITLE
Enhancement: Automatic generation of mock object to satisfy interface

### ISSUE THREAD

**Issue by adriantam** [fiorix/wsdl2go#15]
Probably a good idea to have some way to automatically generate a mock object that satisfy the interface.  This allow easy testing of data that uses the interface.

For example, for the interface Foo
type Foo interface {
   CreateMoo(a *CreateMooRequest) (B *CreateMooResponse, err error)
}

We can generate abc_test.go
type MockFoo struct {
   Err error
   MockCreateMooResponse *CreateMooResponse
}

func (m \* MockFoo) CreateMoo(a *CreateMooRequest) (B *CreateMooResponse, err error) {
    return m.MockCreateMooResponse, m.Err
}

**Comment by fiorix** [comment]
👍

**Comment by fiorix** [comment]
Hey @adriantam is this going anywhere? Otherwise I'll close this ticket.
