### ISSUE TITLE
Error processing WSDL from WS-I

### ISSUE THREAD

**Issue by dimitertodorov** [fiorix/wsdl2go#16]
Just playing with this library. Ran into an issue here and can't figure out why its failing.
https://gist.github.com/dimitertodorov/a8f42549484132cc9ace61f65dafcf71

Getting the following error.
```
2016/09/30 10:22:03 template: interfaceType:11:2: executing "interfaceType" at <.Doc>: can't evaluate field Doc in type *wsdlgo.interfaceTypeFunc
exit status 1
```

**Comment by fiorix** [comment]
Just reproduced with this:

```
$ wsdl2go -i https://gist.githubusercontent.com/dimitertodorov/a8f42549484132cc9ace61f65dafcf71/raw/df8a0affa176553954dfdf60ca08566986ef617d/nnmi_nodes_wsdl.xml
2016/09/30 10:31:57 template: interfaceType:11:2: executing "interfaceType" at <.Doc>: can't evaluate field Doc in type *wsdlgo.interfaceTypeFunc
```

It's failing to execute go's text/template using the structs populated from the wsdl. Something related to documentation, apparently.

**Comment by dimitertodorov** [comment]
What is the following line for?
https://github.com/fiorix/wsdl2go/blob/master/wsdlgo/encoder.go#L308

Removing the "continue" lets the parser run.
Havent actually tested the resulting code.

**Comment by fiorix** [comment]
I've added comments in the commit, check it out. Should probably add a unit test for this.

**Comment by fiorix** [comment]
Just pushed another small change to cleanup my cursing from the code.

**Comment by dimitertodorov** [comment]
Thanks.
Still some bugs. 

Looks like the parser does not handle it well when there is a void/no return but still can return an error.
e.g.
```
// AddCapabilities was auto-generated from WSDL.
AddCapabilities(α string, arg1 *CapabilityArray) (β error)
```

**Comment by fiorix** [comment]
That's correct, unfortunately there are way too many possible cases and I'm not the most experienced wsdl dev.
