### ISSUE TITLE
Invalid package name from WSDL binding

### ISSUE THREAD

**Issue by swordbeta** [fiorix/wsdl2go#18]
```
2016/11/20 23:26:37 generated bad code: 1:21: expected ';', found '.'
    1	package candidatesxs.cfcsoapbinding
```

**Comment by fiorix** [comment]
WSDL has a package name that is incompatible with Go package names. We need a fix in the code generator that can handle that corner case and replace any dots with underbars or nothing. Maybe @adriantam could help out on this? Otherwise I'll take a look whenever I find time next week onwards.
