### ISSUE TITLE
onvif: Can't convert . go file

### ISSUE THREAD

**Issue by CodyGuo** [fiorix/wsdl2go#20]
http://www.onvif.org/Documents/Specifications.aspx
ONVIF WSDL and XML Schemas Specifications
...
http://www.onvif.org/onvif/ver10/events/wsdl/event.wsdl
...

**Comment by fiorix** [comment]
The work done in this commit makes it generate good code that compiles. I have not tested this API but did an extensive manual check between all the WSDLs involved and the generated code.

Let me know if there's anything broken when you use it.

**Comment by CodyGuo** [comment]
Thank you very much, I just came back from the holiday.
After testing found that still can't normal transformation,
Error:
Wsdl2go -i devicemgmt.wsdl -o devicemgmt.go
2017/02/10 13:46:14 WSDL import: Get../../../ ver10 / schema/onvi
F.x sd: unsupported protocol scheme ""

wsdl2go -i accesscontrol.wsdl -o accesscontrol.go
2017/02/10 13:48:04 wsdl import: Get types.xsd: unsupported pro
tocol scheme ""

**Comment by fiorix** [comment]
That error message comes from your WSDL asking to import other WSDLs, in which case we assume to use an HTTP client to do so, and the HTTP client is failing with the `unsupported protocol scheme ""` because of a non-URL entry.

**Comment by CodyGuo** [comment]
https://github.com/quatanium/python-onvif/blob/master/wsdl/events.wsdl
Support external and local WSDL ？

**Comment by fiorix** [comment]
Yeah definitely. If the location does not start with a known schema we should load it from local file. I'd be happy to review this PR.
