### ISSUE TITLE
Generated code cannot unmarshal the response

### ISSUE THREAD

**Issue by chmllr** [fiorix/wsdl2go#21]
I ran into the problem, that the response couldn't be unmarshaled, because you apparently assume, that the `OutputType` token generated in line https://github.com/fiorix/wsdl2go/blob/master/wsdlgo/encoder.go#L490 as `xml:\"{{.OutputType}}\"` is equal for the struct name and in the annotation, which is not the case for my wsdl endpoint. In my case the name of the XML node is _not_ capitalised.

After I changed the xml annotation token to lower-case, the response could be successfully parsed.

I could try to come up with a patch if you'd help me to understand the problem.

Thank you for your work!

**Comment by fiorix** [comment]
Hey I looked at that template few days ago and confirmed what you're saying. Basically we need to preserve the original name of the field from the wsdl to put into the template to be used as the field tag. If you can't figure out (code generation isn't the most straightforward things to do, i get it) at some point whenever i find time will fix it. Otherwise im happy to review any patches.

**Comment by chmllr** [comment]
Thanks a lot for your response! I investigated and came up with this naive fix: https://github.com/chmllr/wsdl2go/commit/ae55cd02032185f14e11be9184f65f176f4a0322

Is it even going into the right direction? Just tell me if I should create a PR or maybe make a few improvement suggestions to my fix. Thanks a lot!

**Comment by fiorix** [comment]
Good stuff. I left some comments in there but in general LGTM.

**Comment by chmllr** [comment]
Thanks a lot! Will fix as you suggested, then test on my wsdl where it failed before, add a test and make a PR in the next weeks.

Btw I had a different problem with the soap client: whenever the status code of the SOAP endpoint was != 200, I received a `nil` as a response because the unmarshaling silently failed. However I'd rather expect a non empty `err` in such case. This is how I fixed it ATM: https://github.com/chmllr/wsdl2go/commit/9f6ce02f6f00235186329dc9e51e2da982b632a4. Do you want this patch too? I personally see no good reason for ignoring the status code.

**Comment by fiorix** [comment]
👍

**Comment by fiorix** [comment]
We can probably close this one now?

**Comment by chmllr** [comment]
Yes absolutely. Thank you.
