### ISSUE TITLE
SoapAction error

### ISSUE THREAD

**Issue by ProgramYazar** [fiorix/wsdl2go#24]
client.go doesnt send soap action, i change roudtrip  function like this (and it works perfectly):
`

// RoundTrip implements the RoundTripper interface.
func (c *Client) RoundTrip(in, out Message) error {
	req := &Envelope{
		EnvelopeAttr: c.Envelope,
		NSAttr:       c.Namespace,
		Header:       c.Header,
		Body:         Body{Message: in},
	}

	if req.EnvelopeAttr == "" {
		req.EnvelopeAttr = "http://schemas.xmlsoap.org/soap/envelope/"
	}
	if req.NSAttr == "" {
		req.NSAttr = c.URL
	}
	var b bytes.Buffer
	err := xml.NewEncoder(&b).Encode(req)
	if err != nil {
		return err
	}
	ct := c.ContentType
	if ct == "" {
		ct = "text/xml"
	}
	cli := c.Config
	if cli == nil {
		cli = http.DefaultClient
	}
	r, err := http.NewRequest("POST", c.URL, &b)
	if err != nil {
		return err
	}
	r.Header.Set("Content-Type", ct)
	r.Header.Add("SOAPAction", fmt.Sprintf("%s/%s", c.Namespace, reflect.TypeOf(in).Elem().Name()))
	if c.Pre != nil {
		c.Pre(r)
	}
	resp, err := cli.Do(r)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		// read only the first Mb of the body in error case
		limReader := io.LimitReader(resp.Body, 1024*1024)
		body, _ := ioutil.ReadAll(limReader)
		return fmt.Errorf("%q: %q", resp.Status, body)
	}
	return xml.NewDecoder(resp.Body).Decode(out)
}

`

I hope this will be helpfull

**Comment by fiorix** [comment]
Want to send a pull request?

**Comment by mitty1987** [comment]
oh no, the head SoapAction led me to a problem：The given SOAPAction ... does not match an operation ！！so, can I set different SoapAction for the head or don't send soapaction?

**Comment by seamuncle** [comment]
I tied the SOAPAction to the WSDL definition for SOAPAction, I think relying on Name isn't strictly accurate for all services (sigh) --do you want to try this branch and see if it does what you need?  https://github.com/seamuncle/wsdl2go --please let us know?

**Comment by mitty1987** [comment]
@seamuncle yeah,it's helpful.or maybe we can add SOAPAction in Client struct,that I think it's more easier.

**Comment by seamuncle** [comment]
Personally, with a WSDL that tells me what SOAPAction to use, I find its not--but we could probably configure the client in such a way that WSDLs without a SOAPAction or misconfigured WSDLs can explicitly override the behaviour--probably a pointer to a simple struct with a "generate SOAPAction header" `bool` and a "header value" `string`  My branch generates a Context that might pass the struct in as well to the same ends.

**Comment by fiorix** [comment]
👍

**Comment by fiorix** [comment]
Fixed by recent patches.
