### ISSUE TITLE
Missing Types

### ISSUE THREAD

**Issue by bstein-clever** [fiorix/wsdl2go#30]
I noticed a few missing types in the generated code after running my WSDL through your library.

WSDL seems like it makes a distinction distinguish between `xs:int` (int32) and `xs:integer` (arbitrarily large integer), but you don't support the latter. I think we could just use math/big.Int for these, though we'd have to keep track before outputting the imports.

Additionally, you don't generate any structs for abstract types (https://github.com/fiorix/wsdl2go/blob/master/wsdlgo/encoder.go#L897), which seems odd to me - if any types depend on these, we end up with compile failures, because it doesn't exist. Was there a reason not to emit types that are abstract?

The same thing goes for `AnySimpleType`,
http://search.cpan.org/dist/SOAP-WSDL/lib/SOAP/WSDL/XSD/Typelib/Builtin.pm#SOAP::WSDL::XSD::Typelib::Builtin::anySimpleType, but I admit that I don't fully understand the SOAP spec, so I'm not clear what it should convert to.

I'm happy to submit PRs for these small changes, but I wasn't sure if there was a reason behind doing them this way, so I didn't want to jump the gun. Suggestions/fixes would be appreciated. Thanks!

**Comment by fiorix** [comment]
Hey these are all valid points. I also don't fully understand the SOAP spec and only wrote the code for what I needed at the time. This has been an on going effort for myself and others that use this code generator.

No reason for not generating abstract structs.. perhaps those should be empty interfaces?

PRs always welcome. :)

**Comment by bstein-clever** [comment]
Seems reasonable to me. There was a case to skip them, but no comment or explanation, so I wasn't sure why. I can make a PR for these; they're both pretty straightforward. I'll get to it a little later today.

**Comment by fiorix** [comment]
👍
