### ISSUE TITLE
Question. Local dependencies.

### ISSUE THREAD

**Issue by IAD** [fiorix/wsdl2go#31]
Some WSDL files have link on local dependencies(the same directory), like:
      <xsd:import namespace="http://test.net/AdminAPI_Admin" schemaLocation="test.net.AdminAPI_Admin.xsd" />

In this case we have the error:
wsdl import: Get test.net.AdminAPI_Admin.wsdl: unsupported protocol scheme ""
If I'm right - this is a error from net/http

Do we need to bug fix something or I can just fast-fix something in my WSDL file?

**Comment by IAD** [comment]
looks like we can update the goEncoder.importRemote() to work with local files too

**Comment by fiorix** [comment]
Yes, the current implementation expects it to be a URL thus the missing schema error. I don't mind supporting both local files and URLs. Would be happy to review PRs.

**Comment by IAD** [comment]
ok, on it

**Comment by IAD** [comment]
@fiorix please review

**Comment by fiorix** [comment]
Crickets here. I'm happy to reopen if you plan to continue.

**Comment by IAD** [comment]
Hello. Not needed, thanks.
