### ISSUE TITLE
Unreachable code when encoder should generate nested ComplexType

### ISSUE THREAD

**Issue by arkadiam** [fiorix/wsdl2go#38]
In wsdl2go/wsdlgo/encoder.go at line 1040 there is a code:

```
	if el.Type == "" {
		el.Type = "string"
	}
	var slicetype string
	if el.Type == "" && el.ComplexType != nil {
         ...
        }
```

Second "if" will never evaluate to true because when el.Type is empty it'll be set to "string" in the first "if". That will generated all nested complex types as "string" instead of proper types.

Possibly the proper logic should be:
```
	if el.Type == "" {
		if el.ComplexType != nil {
		...
		} else {
			el.Type = "string"
		}
	}
```

**Comment by fiorix** [comment]
Good point. PR?

**Comment by arkadiam** [comment]
Thanks. I've submitted PR.
