### ISSUE TITLE
Unable to process wsdl file

### ISSUE THREAD

**Issue by vodolaz095** [fiorix/wsdl2go#5]
I try to process this WSDL file (the one from UPS delivery)
https://gist.github.com/vodolaz095/732a0822902b1cb06dd592adbf359e32

I receive this error:

```
panic: template: interfaceType:10: illegal number syntax: "-"

goroutine 1 [running]:
text/template.Must(0x0, 0x7f15fa332000, 0xc820076e00, 0x0)
    /usr/lib/golang/src/text/template/helper.go:23 +0x4b
github.com/fiorix/wsdl2go/wsdlgo.init()
    /home/vodolaz095/go/src/github.com/fiorix/wsdl2go/wsdlgo/encoder.go:269 +0xe6
main.init()
    /home/vodolaz095/go/src/github.com/fiorix/wsdl2go/main.go:87 +0x68

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/lib/golang/src/runtime/asm_amd64.s:1721 +0x1
```

I use Linux and Go of version `go version go1.5.4 linux/amd64`

**Comment by fiorix** [comment]
I didn't panic for me, instead printed out the error. For some reason it cannot figure out the type of `ClientInformationType` for example, then running `gofmt` on the code (which is automatic) fails because of this definition:

```
// ClientInformationType was auto-generated from WSDL.                          
type ClientInformationType struct {                                             
Property []* `xml:"Property,omitempty" json:"Property,omitempty" yaml:"Property,omitempty"`                                                                                                                                                   
}                                                                               
```

This is definitely one of the millions of corner cases of SOAP complex types.

**Comment by fiorix** [comment]
With the latest changes it generates the correct code. I have not tried to hit the API to see the results though. Please give it a try and let us know. If the problem persists we can re-open this.
