### ISSUE TITLE
SetXMLType on interface

### ISSUE THREAD

**Issue by adriantam** [fiorix/wsdl2go#55]
The encoder should not encode the SetXMLType object if the complexType itself is abstract.  Otherwise, the generated go file cannot compile because you cannot assign TypeAttrXSI and TypeNamespace to it.

Currently, the following is generated:

> 
> // BulkOperationRequest was auto-generated from WSDL.
> type BulkOperationRequest interface{}
> 
> // SetXMLType was auto-generated from WSDL.
> func (t *BulkOperationRequest) SetXMLType() {
>         t.TypeAttrXSI = "objtype:BulkOperationRequest"
>         t.TypeNamespace = "http://www.example.com"
> }

**Comment by fiorix** [comment]
👍
