### ISSUE TITLE
Expected go version

### ISSUE THREAD

**Issue by adriantam** [fiorix/wsdl2go#58]
What is the expected go version?  

The [.travis.yml](https://github.com/fiorix/wsdl2go/blob/master/.travis.yml) file suggests that all test must pass with go 1.6-1.9.  However, the [package_test.go](https://github.com/fiorix/wsdl2go/blob/master/wsdlgo/package_test.go) file uses golang 1.8+ feature (such as test.Name etc.).

**Comment by turboezh** [comment]
I've fixed the test in #57. My fault, sorry.

**Comment by adriantam** [comment]
ok.  I'll close issue then.

**Comment by turboezh** [comment]
It's subject to discuss still. I think support of old go versions may be dropped.

**Comment by fiorix** [comment]
It's probably ok the way it is now, including old go versions.
At some point we might revisit this decision.
