### ISSUE TITLE
How to set SOAP Headers?

### ISSUE THREAD

**Issue by 17thcamel** [fiorix/wsdl2go#6]
Thanks for wsdl2go! 
So, I used wsdl2go and generated awesome set of types for my huge wsdl (which I cannot post here.) However, the service I am trying to hit expects certain custom headers to be present. I can set them in any of my SOAP clients that I use and it goes fine. But, I did not find how to set those headers. I wrote a simple go test like so:
```

func TestMakeClient(t *testing.T) {
        request := new(MyDoSomethingRequest)
        client := soap.Client{
                URL:         "<valid-url-here>",
                Namespace:   Namespace,
                ContentType: "text/xml",
        }
        svcPort := NewMyServicePort(&client)
        resp, err := svcPort.MyDoSomething(request)
        if err != nil {
                t.Fatalf("nil response received. %s", err.Error())
        } 
}
```
I get back errors from my service saying certain headers missing. How do I get a hook to set headers in `soap.Client.Config` `http` client? Thanks!

**Comment by fiorix** [comment]
This change should do. I've also added unit tests, it had none for the client... having to modify the http header is something I didn't need before but I see the point.

Most of the services I connect to with this code are internal stuff, at most they need a header in the soap envelope.

**Comment by 17thcamel** [comment]
Thanks.
