### ISSUE TITLE
Case mismatch in generated `xml:` for responses

### ISSUE THREAD

**Issue by 17thcamel** [fiorix/wsdl2go#7]
From my wsdl, I have one of the operations in `types.go` generated like so for one `myOperation`:
```
type MyServicePort interface {
  // MyOperation was auto-generated from WSDL.
  func (p *myServicePort) MyOperation(α *MyOperationRequest) (β *MyOperationResponse, err error) {
  	γ := struct {
		XMLName xml.Name `xml:"Envelope"`
		Body    struct {
			M MyOperationResponse `xml:"MyOperationResponse"`
		}
	}{}
	if err = p.cli.RoundTrip(α, &γ); err != nil {
		return nil, err
	}
	return &γ.Body.M, nil
  }
}
```
The response type is like so:
```
type MyOperationResponse struct {
  Ack string `xml:"ack,omitempty" json:"ack,omitempty" yaml:"ack,omitempty"`
  ... // more omitted
}
```
Server returns XML response for `myOperation` like so:
```
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">   
  <soapenv:Header />
   <soapenv:Body>
    <myOperation xmlns="http://www.my.com/somenamespace">
      <ack>Failure</ack>
      <!-- omitted -->
    </myOperation>
  </soapenv:Body>
</soapenv:Envelope>
```
Please note, that the case for `myOperation` is different from what is defined in the `γ struct` in `func MyOperation(...)` Now, upon calling `MyOperation` always an empty response object is returned. No errors too. Turns out, if I change the case of `xml:"MyOperation"` to `xml:"myOperation"` in generated types go file - parsing works fine and I get back a response object with all fields set properly. My question is: is this case mismatch while generating code ? or Is something wrong with my wsdl ?

thanks!

**Comment by 17thcamel** [comment]
Update:
wsdl snippet for element mentioned above looks like so:
```
<xs:element name="createListingDraftResponse" type="tns:CreateListingDraftResponse"/>
  <xs:complexType name="CreateListingDraftResponse">
    <xs:annotation>
      <xs:documentation>Document goes here</xs:documentation>
        </xs:annotation>
   ...
```

**Comment by fiorix** [comment]
Looks like a case and name mismatch in the generated code at first glance.

**Comment by scottjbarr** [comment]
Let me know if any issues with the above.

**Comment by scottjbarr** [comment]
This should be OK to close now that #7 has been merged.
