### ISSUE TITLE
wsdl's SoapAction not respected for Soap1.1

### ISSUE THREAD

**Issue by adriantam** [fiorix/wsdl2go#70]
In Soap1.1, the soapAction header is set to the object's name even if the wsdl specifies the soapAction name.

For example, the following wsdl snippet
<operation name="ModifyObj">
<soap:operation soapAction="http://soap.example.com"/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
<fault name="WsValidationException">
<soap:fault name="WsValidationException" use="literal"/>
</fault>
</operation>

will generate 
	if err = p.cli.RoundTripWithAction("ModifyObj", α, &γ); err != nil {
		return nil, err
	}
	return &γ.Body.M, nil

instead, I should expect 
	if err = p.cli.RoundTripWithAction("http://soap.example.com", α, &γ); err != nil {
		return nil, err
	}
	return &γ.Body.M, nil

**Comment by fiorix** [comment]
👍
