### ISSUE TITLE
Allow configuration on whether XMLName is generated

### ISSUE THREAD

**Issue by adriantam** [fiorix/wsdl2go#84]
Changes brought in by  #75 hardcoded encoder.go such that XMLName is not generated.  This should be made configurable.

**Comment by Kernle32DLL** [comment]
@adriantam do you have a use case where this is needed? For me this created configurations which were not marshallable. This might be an issue with my wsdl tho, so it would be nice to know where this might be needed.

**Comment by fiorix** [comment]
Please rebase from master since I believe #88 should fix this.

**Comment by fiorix** [comment]
stale, closing
