### ISSUE TITLE
Stucks while Unmarshaling

### ISSUE THREAD

**Issue by Arman92** [fiorix/wsdl2go#91]
I've got this wsdl file: [http://pardano.com/p/webservice/?wsdl   ](http://pardano.com/p/webservice/?wsdl   )

And when I try to run wsdl2go on this file, it sticks on line 71 of main.go ([this line](https://github.com/fiorix/wsdl2go/blob/0a23ddef1d62e202d86483e3b4a02b847b79336f/main.go#L71))

Any Idea why?

**Comment by fiorix** [comment]
How are you running it?

it should be `wsdl2go -i <url>` otherwise it'll try to read from stdin.

**Comment by fiorix** [comment]
no answer, closing
