### ISSUE TITLE
Add support for <xsd:choice>

### ISSUE THREAD

**Issue by nlacey** [fiorix/wsdl2go#92]
https://www.w3schools.com/xml/el_choice.asp

you handle sequence, but not <xsd:choice>
Any object that is enclosed within a choice, end up with an empty object body. 

[localimport_choice_broken_xsd.txt](https://github.com/fiorix/wsdl2go/files/1737833/localimport_choice_broken_xsd.txt)

**Comment by fiorix** [comment]
Hey I have no plans to implement this any time soon. Happy to review PRs tho.

**Comment by nlacey** [comment]
ok, I got part of the way there yesterday

**Comment by nlacey** [comment]
I've create PR https://github.com/fiorix/wsdl2go/pull/93

**Comment by fiorix** [comment]
Landed.
